name = "note-editor"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "functions/api/[[path]].ts"

[assets]
directory = "./build"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "note-editor-db"
database_id = "c633c65e-4033-4ae7-ba5b-d753e1cb557e"
migrations_dir = "migrations"
