import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  layout: {
    display: "flex",
    height: "100vh",
    overflow: "hidden",
    padding: "12px",
    gap: "10px",
    background: "var(--app-shell-bg)",
  },
  mobileTabs: {
    display: "flex",
    gap: "6px",
    padding: "6px",
    marginBottom: "2px",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-lg)",
    background: "var(--app-panel-bg-strong)",
    boxShadow: "var(--shadow-sm)",
  },
  mobileTabButton: {
    flex: 1,
    minHeight: "44px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--color-border)",
    color: "var(--color-text-secondary)",
    background: "transparent",
    fontWeight: 600,
  },
  mobileTabButtonActive: {
    background: "var(--color-bg-emphasis)",
    color: "var(--color-text-inverse)",
    borderColor: "var(--color-bg-emphasis)",
    boxShadow: "var(--shadow-sm)",
  },
  sidebar: {
    width: "224px",
    flexShrink: 0,
    background: "var(--app-panel-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-lg)",
    boxShadow: "var(--shadow-sm), var(--shadow-inset)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  sidebarHeader: {
    padding: "14px",
    borderBottom: "1px solid var(--color-border-subtle)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoutBtn: {
    fontSize: "11px",
    color: "var(--color-text-secondary)",
    cursor: "pointer",
    background: "var(--app-control-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "999px",
    padding: "6px 9px",
    fontWeight: 700,
  },
  userInfo: {
    padding: "10px 14px",
    fontSize: "12px",
    color: "var(--color-text-secondary)",
    borderBottom: "1px solid var(--color-border-subtle)",
  },
  groupSectionHeader: {
    padding: "10px 14px 6px",
    borderBottom: "1px solid var(--color-border-subtle)",
    background: "transparent",
  },
  groupSection: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
    minHeight: 0,
  },
  groupRow: {
    display: "flex",
    alignItems: "center",
    margin: "2px 0",
    borderRadius: "var(--radius-md)",
  },
  activeGroup: {
    background: "var(--color-bg-emphasis)",
    color: "var(--color-text-inverse)",
    boxShadow: "var(--shadow-sm)",
  },
  groupSelectButton: {
    flex: 1,
    minHeight: "44px",
    padding: "8px 10px",
    textAlign: "left",
    color: "inherit",
    fontSize: "13px",
  },
  iconBtn: {
    background: "none",
    color: "inherit",
    opacity: 0.7,
    fontSize: "12px",
    lineHeight: 1,
    minWidth: "48px",
    minHeight: "44px",
  },
  groupActionButtons: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    paddingRight: "4px",
  },
  newGroupForm: {
    flexShrink: 0,
    display: "flex",
    padding: "10px",
    borderTop: "1px solid var(--color-border-subtle)",
    gap: "6px",
  },
  groupInput: {
    flex: 1,
    minWidth: 0,
    minHeight: "44px",
    padding: "8px 10px",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-md)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-primary)",
    fontSize: "12px",
    outline: "none",
  },
  addBtn: {
    minWidth: "44px",
    minHeight: "44px",
    background: "var(--color-bg-emphasis)",
    color: "var(--color-text-inverse)",
    border: "none",
    borderRadius: "var(--radius-md)",
    cursor: "pointer",
    fontWeight: 700,
  },
  noteList: {
    width: "328px",
    flexShrink: 0,
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-lg)",
    boxShadow: "var(--shadow-sm), var(--shadow-inset)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--app-panel-bg)",
  },
  noteListHeader: {
    padding: "14px",
    borderBottom: "1px solid var(--color-border-subtle)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "var(--app-panel-bg-strong)",
  },
  noteListBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  noteListMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  reorderHint: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
  },
  newNoteBtn: {
    fontSize: "12px",
    minHeight: "44px",
    padding: "4px 14px",
    background: "var(--color-bg-emphasis)",
    color: "var(--color-text-inverse)",
    border: "none",
    borderRadius: "999px",
    cursor: "pointer",
  },
  noteSearchRow: {
    display: "flex",
    gap: "8px",
    padding: "12px 14px",
    borderBottom: "1px solid var(--color-border-subtle)",
    background: "var(--app-panel-bg-strong)",
  },
  noteSearchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: "40px",
    padding: "8px 10px",
    borderRadius: "999px",
    border: "1px solid var(--color-border-subtle)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-primary)",
    fontSize: "13px",
    outline: "none",
  },
  noteSearchClearBtn: {
    minHeight: "40px",
    padding: "8px 12px",
    borderRadius: "999px",
    border: "1px solid var(--color-border-subtle)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-secondary)",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  empty: {
    padding: "20px 12px",
    color: "var(--color-text-secondary)",
    fontSize: "13px",
    textAlign: "center",
  },
  noteItem: {
    padding: "10px 12px",
    borderBottom: "1px solid var(--color-border)",
    cursor: "pointer",
    background: "var(--app-panel-bg-strong)",
  },
  noteRow: {
    display: "flex",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: "8px",
  },
  noteSelectButton: {
    minWidth: 0,
    flex: 1,
    textAlign: "left",
    padding: "0",
    minHeight: "44px",
  },
  activeNote: {
    background: "var(--app-active-bg)",
    boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--color-brand-primary) 28%, transparent)",
    color: "var(--color-text-primary)",
  },
  noteTitle: {
    fontWeight: 500,
    fontSize: "13px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--color-text-primary)",
  },
  noteDate: {
    fontSize: "11px",
    color: "var(--color-text-secondary)",
    marginTop: "2px",
  },
  noteActions: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
  },
  noteActionsCompact: {
    gap: "2px",
  },
  noteGroupMoveRow: {
    marginTop: "8px",
  },
  noteGroupMoveSelect: {
    width: "100%",
    minHeight: "36px",
    padding: "4px 8px",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius)",
    background: "var(--color-bg)",
    color: "var(--color-text-primary)",
    fontSize: "12px",
  },
  orderBtn: {
    background: "none",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius)",
    color: "var(--color-text-secondary)",
    fontSize: "12px",
    lineHeight: 1,
    minWidth: "44px",
    minHeight: "44px",
  },
  orderBtnCompact: {
    minWidth: "28px",
    minHeight: "28px",
    fontSize: "11px",
  },
  deleteBtn: {
    background: "none",
    border: "1px solid transparent",
    borderRadius: "var(--radius)",
    color: "var(--color-text-secondary)",
    fontSize: "16px",
    lineHeight: 1,
    minWidth: "44px",
    minHeight: "44px",
  },
  deleteBtnCompact: {
    minWidth: "28px",
    minHeight: "28px",
    fontSize: "14px",
  },
  editor: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-lg)",
    background: "var(--app-panel-bg-strong)",
    boxShadow: "var(--shadow-sm), var(--shadow-inset)",
  },
  editorToolbar: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    padding: "14px 18px",
    borderBottom: "1px solid var(--color-border-subtle)",
    background: "var(--app-panel-bg-strong)",
    gap: "12px",
  },
  titleInput: {
    flex: 1,
    minWidth: "180px",
    border: "none",
    outline: "none",
    fontSize: "22px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    background: "transparent",
    color: "var(--color-text-primary)",
  },
  groupPicker: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  groupPickerLabel: {
    fontSize: "11px",
    color: "var(--color-text-secondary)",
  },
  groupPickerSelect: {
    minHeight: "36px",
    padding: "4px 8px",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-md)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-primary)",
  },
  toolbarRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexShrink: 0,
    marginLeft: "auto",
  },
  statusBadge: {
    fontSize: "12px",
  },
  charCount: {
    fontSize: "12px",
    color: "var(--color-text-secondary)",
  },
  secondaryActionBtn: {
    minHeight: "36px",
    padding: "4px 10px",
    borderRadius: "999px",
    border: "1px solid var(--color-border-subtle)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-primary)",
    fontSize: "12px",
    fontWeight: 600,
  },
  copyBtn: {
    minHeight: "44px",
    padding: "4px 12px",
    color: "var(--color-brand-contrast)",
    border: "none",
    borderRadius: "999px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  textarea: {
    flex: 1,
    padding: "clamp(24px, 5vw, 56px)",
    border: "none",
    outline: "none",
    resize: "none",
    fontSize: "16px",
    lineHeight: 1.85,
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--color-bg-surface) 82%, transparent), var(--color-bg-canvas))",
    color: "var(--color-text-primary)",
  },
  noNote: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    padding: "32px",
    color: "var(--color-text-secondary)",
    fontSize: "16px",
    background:
      "radial-gradient(circle at 50% 35%, var(--color-bg-accent-soft), transparent 34%), var(--color-bg-canvas)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(24, 33, 29, 0.52)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    zIndex: 1000,
  },
  modalCard: {
    width: "min(720px, 100%)",
    background: "var(--color-bg-surface)",
    borderRadius: "var(--radius-xl)",
    padding: "24px",
    boxShadow: "var(--shadow-lg)",
    border: "1px solid var(--color-border-subtle)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  modalTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: 700,
    color: "var(--color-text-primary)",
  },
  modalDescription: {
    margin: 0,
    fontSize: "14px",
    lineHeight: 1.6,
    color: "var(--color-text-secondary)",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    flexWrap: "wrap",
  },
  modalPrimaryButton: {
    minHeight: "44px",
    padding: "10px 14px",
    borderRadius: "var(--radius)",
    border: "none",
    background: "var(--color-bg-emphasis)",
    color: "var(--color-text-inverse)",
    fontWeight: 700,
  },
  modalSecondaryButton: {
    minHeight: "44px",
    padding: "10px 14px",
    borderRadius: "var(--radius)",
    border: "1px solid var(--color-border)",
    background: "var(--app-control-bg)",
    color: "var(--color-text-primary)",
    fontWeight: 600,
  },
  modalGhostButton: {
    minHeight: "44px",
    padding: "10px 14px",
    borderRadius: "var(--radius)",
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--color-text-secondary)",
    fontWeight: 600,
  },
  conflictGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "12px",
  },
  conflictPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "12px",
    borderRadius: "12px",
    background: "var(--app-control-bg)",
    border: "1px solid var(--color-border)",
  },
  conflictPanelTitle: {
    fontSize: "13px",
    color: "var(--color-text-primary)",
  },
  conflictPanelMeta: {
    fontSize: "12px",
    color: "var(--color-text-secondary)",
  },
  conflictPanelBody: {
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxHeight: "220px",
    overflowY: "auto",
    fontSize: "13px",
    lineHeight: 1.6,
    color: "var(--color-text-primary)",
  },
};
